### ISSUE TITLE
Compile Errors RPI2

### ISSUE THREAD

**Issue by KMFDManic** [libretro/superbroswar-libretro#1]
Thanks for opening up the issues here.  I have gotten it to work successfully on one platform I utilize.  But, on rpi2, it generates this error when attempting to run it:

[ERROR] Failed to open libretro core: "/etc/libretro/core/superbroswar_libretro.so"
[ERROR] Error(s): /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /etc/libretro/core/superbroswar_libretro.so)

Is this similar to the Vita Static Link issue, or something else entirely?  This "variant" of the jump n bump gameplay definitely reigns supreme.  Very impressed by the sheer number of maps.  I wonder if, when I did my video, you seeing me referring to it as a Mario Battle game, inspired you:)  Anyways, thanks so much in advance!  I would love to have this working for retropie 2 as well!

Showcase of the game:)  https://www.youtube.com/watch?v=YoV2e6ObjX8

**Comment by keithbowes** [comment]
It's linking against a newer version of libstdc++ than it's loading at runtime?  Maybe you can set `LD_LIBRARY_PATH` to get it to use the new version at runtime.

It compiles and finds all symbols for me (on Linux), but I get the error: `ERROR: Empty map directory!`.  I tried to follow the source code and put the maps from testmaps.zip in ~/.config/retroarch/saves/superbroswar/maps, but no luck (I'd assume that they would go in the system directory like xrick data files do, but that's not what the source code indicates).  I suppose we should wait until there's a README indicating how to use it before worrying too much about it being compilable and/or usable.

**Comment by KMFDManic** [comment]
@keithbowes I actually got the game working fine.  At the tail end of my issue, I link to a demonstration of it running.  What would be awesome, is if you use Discord, and are able to join the one I am at.  We can go over a few things, and I will get you up and running with this masterpiece!

I am KMFDManic there, as well.  You can just shoot me a pm once you join, and we can go from there!

https://discord.gg/MHbVBuSgvu

**Comment by loki666** [comment]
/usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found

this looks like a cross-compiling issue, the compiler you are using is linking with a libstdc++.so.6 version different than the one used when running the core.
Maybe there is an issue with the toolchain you are using... I can't really help you with that

**Comment by loki666** [comment]
> It's linking against a newer version of libstdc++ than it's loading at runtime? Maybe you can set `LD_LIBRARY_PATH` to get it to use the new version at runtime.
> 
> It compiles and finds all symbols for me (on Linux), but I get the error: `ERROR: Empty map directory!`. I tried to follow the source code and put the maps from testmaps.zip in ~/.config/retroarch/saves/superbroswar/maps, but no luck (I'd assume that they would go in the system directory like xrick data files do, but that's not what the source code indicates). I suppose we should wait until there's a README indicating how to use it before worrying too much about it being compilable and/or usable.

You need to create a smw.game empty file in the data folder, and load that file as a RetroArch content

**Comment by keithbowes** [comment]
> 
> You need to create a smw.game empty file in the data folder, and load that file as a RetroArch content

I'll try it. If I get it to work, I'll try to send a PR for a README.
